name = "navidad-en-cojines-inventory"
main = "worker.js"
compatibility_date = "2026-10-03"
workers_dev = true

[vars]
GITHUB_OWNER = "lunarm24"
GITHUB_REPO = "Navidad-en-cojines"
GITHUB_BRANCH = "main"
ALLOWED_ORIGINS = "https://lunarm24.github.io,http://localhost:8080"
